apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: dallasformularacing/actions-test_flask-app:0164aca767c881fdbd6405fa4ebeb280947b0ddc
        ports:
        - containerPort: 5000
