# Stage 1: Build
FROM node:20-slim AS build
WORKDIR /app

# Install dependencies first ("layer caching"??)
COPY frontend/package*.json ./
RUN npm ci

# Copy source -> build
COPY frontend/ .
RUN npm run build


# Stage 2: Listen for browser request and hand over files ("serving"?)
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Pass API URL to  built app at runtime
ENV VITE_API_URL=http://car-sensor-api-svc

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]